# Milestone 1 - Understand the data and Project Setup

# Milestone 2 - Data Inspection

In [1]:
import pandas as pd
import numpy as np

## 2.1 Load the Dataset

In [2]:
raw_df = pd.read_csv("cafe_sales_dataset.csv")
df = raw_df.copy()

## 2.2 Inspect Dataset Structure

In [3]:
df.shape

(10000, 8)

In [4]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

In [6]:
df.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2,4,Credit Card,Takeaway,9/8/2023
1,TXN_4977031,Cake,4,3,12,Cash,In-store,5/16/2023
2,TXN_4271903,Cookie,4,1,ERROR,Credit Card,In-store,7/19/2023
3,TXN_7034554,Salad,2,5,10,UNKNOWN,UNKNOWN,4/27/2023
4,TXN_3160411,Coffee,2,2,4,Digital Wallet,In-store,6/11/2023
5,TXN_2602893,Smoothie,5,4,20,Credit Card,NaN,3/31/2023
6,TXN_4433211,UNKNOWN,3,3,9,ERROR,Takeaway,10/6/2023
7,TXN_6699534,Sandwich,4,4,16,Cash,UNKNOWN,10/28/2023
8,TXN_4717867,NaN,5,3,15,NaN,Takeaway,7/28/2023
9,TXN_2064365,Sandwich,5,4,20,NaN,In-store,12/31/2023

# Milestone 3 - Data Quality Check

## 3.1 Missing Value Check

In [7]:
df.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

## 3.2 Duplicate Row Check

In [8]:
df.duplicated().sum()

np.int64(0)

## 3.3 Data Type Validation

In [9]:
df.dtypes

Transaction ID      str
Item                str
Quantity            str
Price Per Unit      str
Total Spent         str
Payment Method      str
Location            str
Transaction Date    str
dtype: object

## 3.4 Invalid Value Check

In [10]:
columns_to_check = [
    "Item",
    "Quantity",
    "Price Per Unit",
    "Total Spent",
    "Payment Method",
    "Location",
    "Transaction Date"
]

for col in columns_to_check:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(15))

--- Item ---
Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64

--- Quantity ---
Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
NaN         138
Name: count, dtype: int64

--- Price Per Unit ---
Price Per Unit
3          2429
4          2331
2          1227
5          1204
1          1143
1.5        1133
ERROR       190
NaN         179
UNKNOWN     164
Name: count, dtype: int64

--- Total Spent ---
Total Spent
6      979
12     939
3      930
4      923
20     746
15     734
8      677
10     524
2      497
9      479
5      468
16     444
25     259
7.5    237
1      232
Name: count, dtype: int64

--- Payment Method ---
Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64

--- Location ---
Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

--- Transaction Date ---
Transaction Date
NaN           159
UNKNOWN       159
ERROR         142
2/6/2023       40
6/16/2023      40
3/13/2023      39
7/21/2023      39
7/24/2023      39
9/21/2023      39
1/5/2023       38
6/18/2023      37
10/22/2023     37
1/25/2023      37
11/7/2023      36
4/30/2023      36
Name: count, dtype: int64

## 3.5 Categorial Consistency Check

In [11]:
categorical_cols = [
    "Item",
    "Payment Method",
    "Location"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print(sorted(df[col].dropna().unique()))

--- Item ---
['Cake', 'Coffee', 'Cookie', 'ERROR', 'Juice', 'Salad', 'Sandwich', 'Smoothie', 'Tea', 'UNKNOWN']

--- Payment Method ---
['Cash', 'Credit Card', 'Digital Wallet', 'ERROR', 'UNKNOWN']

--- Location ---
['ERROR', 'In-store', 'Takeaway', 'UNKNOWN']

## 3.6 Outlier and Unrealistic Value Check

In [12]:
numeric_cols = [
    "Quantity",
    "Price Per Unit",
    "Total Spent"
]

for col in numeric_cols:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Quantity ---
Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
NaN         138
Name: count, dtype: int64

--- Price Per Unit ---
Price Per Unit
3          2429
4          2331
2          1227
5          1204
1          1143
1.5        1133
ERROR       190
NaN         179
UNKNOWN     164
Name: count, dtype: int64

--- Total Spent ---
Total Spent
6          979
12         939
3          930
4          923
20         746
15         734
8          677
10         524
2          497
9          479
5          468
16         444
25         259
7.5        237
1          232
4.5        225
1.5        205
NaN        173
UNKNOWN    165
ERROR      164
Name: count, dtype: int64

## 3.7 Business Rule Validation

The expected business rule is:

Total Spent = Quantity × Price Per Unit

In [13]:
# No calculation is needed in this milestone because the columns are not yet ready for reliable numeric comparison.

# Milestone 4 - Data Cleaning

## Initialize the working DataFrame

In [14]:
df = raw_df.copy()

## 4.1 Convert Numeric Columns

In [15]:
numeric_cols = ["Quantity", "Price Per Unit", "Total Spent"]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.astype({
    "Quantity": "Int64",
    "Price Per Unit": "float64",
    "Total Spent": "float64"
})

In [16]:
df[numeric_cols].dtypes

Quantity            Int64
Price Per Unit    float64
Total Spent       float64
dtype: object

In [17]:
df[numeric_cols].isna().sum()

Quantity          479
Price Per Unit    533
Total Spent       502
dtype: int64

## 4.2 Recover missing quantity Values

In [18]:
# Use the business rule:

# Quantity = Total Spent / Price Per Unit

recoverable_qty = (
    df["Quantity"].isna()
    & df["Price Per Unit"].notna()
    & df["Total Spent"].notna()
    & df["Price Per Unit"].gt(0)
)

recoverable_qty.sum()

np.int64(441)

In [19]:
calculated_qty = (
    df.loc[recoverable_qty, "Total Spent"]
    / df.loc[recoverable_qty, "Price Per Unit"]
)

non_whole_qty = ~np.isclose(
    calculated_qty,
    calculated_qty.round()
)

non_whole_qty.sum()

np.int64(0)

In [20]:
if non_whole_qty.any():
    raise ValueError("Some calculated quantities are not whole numbers.")

df.loc[recoverable_qty, "Quantity"] = (
    calculated_qty.round().astype("Int64")
)

df["Quantity"].isna().sum()

np.int64(38)

## 4.3 Recover Missing Price Per Unit Values

In [21]:
# Use the business rule:

# Price Per Unit = Total Spent / Quantity

recoverable_price = (
    df["Price Per Unit"].isna()
    & df["Quantity"].notna()
    & df["Total Spent"].notna()
    & df["Quantity"].gt(0)
)

recoverable_price.sum()

np.int64(495)

In [22]:
calculated_price = (
    df.loc[recoverable_price, "Total Spent"]
    / df.loc[recoverable_price, "Quantity"]
)

calculated_price.describe()

count       495.0
mean     2.908081
std      1.305212
min           1.0
25%           1.5
50%           3.0
75%           4.0
max           5.0
dtype: Float64

In [23]:
df.loc[recoverable_price, "Price Per Unit"] = calculated_price

df["Price Per Unit"].isna().sum()

np.int64(38)

## 4.4 Recover Missing Total Spent Values

In [24]:
# Use the business rule:

# Total Spent = Quantity × Price Per Unit

recoverable_total = (
    df["Total Spent"].isna()
    & df["Quantity"].notna()
    & df["Price Per Unit"].notna()
    & df["Quantity"].gt(0)
)

recoverable_total.sum()

np.int64(462)

In [25]:
calculated_total = (
    df.loc[recoverable_total, "Quantity"]
    * df.loc[recoverable_total, "Price Per Unit"]
)

calculated_total.describe()

count       462.0
mean     9.066017
std      5.896198
min           1.0
25%           4.0
50%           8.0
75%          12.0
max          25.0
dtype: Float64

In [26]:
df.loc[recoverable_total, "Total Spent"] = calculated_total

df["Total Spent"].isna().sum()

np.int64(40)

## 4.5 Standardize/Clean the Item column

In [27]:
df["Item"] = df["Item"].replace({
    "ERROR": "Unknown",
    "UNKNOWN": "Unknown"
})

df["Item"] = df["Item"].fillna("Unknown")

df["Item"].value_counts(dropna=False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
Unknown      969
Name: count, dtype: int64

## 4.6 Standardize/Clean categorical columns(Payment Method and Location)

In [28]:
text_cols = ["Payment Method", "Location"]

for col in text_cols:
    df[col] = df[col].replace(["ERROR", "UNKNOWN"], "Unknown")
    df[col] = df[col].fillna("Unknown")

for col in text_cols:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

Payment Method:
Payment Method
Unknown           3178
Digital Wallet    2291
Credit Card       2273
Cash              2258
Name: count, dtype: int64

Location:
Location
Unknown     3961
Takeaway    3022
In-store    3017
Name: count, dtype: int64

## 4.7 Convert transaction dates

In [29]:
df["Transaction Date"] = df["Transaction Date"].replace(
    ["ERROR", "UNKNOWN"], np.nan
)

df["Transaction Date"] = pd.to_datetime(
    df["Transaction Date"],
    format="%m/%d/%Y",
    errors="coerce"
)

print("Data type:", df["Transaction Date"].dtype)
print("Missing dates:", df["Transaction Date"].isna().sum())

Data type: datetime64[us]
Missing dates: 460

## 4.8 Set Text Column Data Types

In [30]:
df["Transaction ID"] = df["Transaction ID"].astype("string")

text_cols = ["Item", "Payment Method", "Location"]
df[text_cols] = df[text_cols].astype("string")

df.dtypes

Transaction ID              string
Item                        string
Quantity                     Int64
Price Per Unit             float64
Total Spent                float64
Payment Method              string
Location                    string
Transaction Date    datetime64[us]
dtype: object

## 4.9 Final Data Quality Validation

In [31]:
df.dtypes

Transaction ID              string
Item                        string
Quantity                     Int64
Price Per Unit             float64
Total Spent                float64
Payment Method              string
Location                    string
Transaction Date    datetime64[us]
dtype: object

In [32]:
df.isna().sum()

Transaction ID        0
Item                  0
Quantity             38
Price Per Unit       38
Total Spent          40
Payment Method        0
Location              0
Transaction Date    460
dtype: int64

In [33]:
df["Transaction ID"].duplicated().sum()

np.int64(0)

In [34]:
valid_rows = (
    df["Quantity"].notna()
    & df["Price Per Unit"].notna()
    & df["Total Spent"].notna()
)

mismatch = ~np.isclose(
    df.loc[valid_rows, "Total Spent"],
    df.loc[valid_rows, "Quantity"]
    * df.loc[valid_rows, "Price Per Unit"]
)

mismatch.sum()

np.int64(0)

In [35]:
df.shape

(10000, 8)

# Milestone 5 - Data Transformation

## 5.1 Create a Transformation Dataset

In [36]:
transformed_df = df.copy()

transformed_df.shape

(10000, 8)

## 5.2 Create Revenue Column

In [37]:
transformed_df["Revenue"] = transformed_df["Total Spent"]

transformed_df[["Total Spent", "Revenue"]].head(10)

   Total Spent  Revenue
0          4.0      4.0
1         12.0     12.0
2          4.0      4.0
3         10.0     10.0
4          4.0      4.0
5         20.0     20.0
6          9.0      9.0
7         16.0     16.0
8         15.0     15.0
9         20.0     20.0

## 5.3 Extract Month from Transaction Date

In [38]:
transformed_df["Month"] = transformed_df["Transaction Date"].dt.month

transformed_df[["Transaction Date", "Month"]].head(10)

  Transaction Date  Month
0       2023-09-08    9.0
1       2023-05-16    5.0
2       2023-07-19    7.0
3       2023-04-27    4.0
4       2023-06-11    6.0
5       2023-03-31    3.0
6       2023-10-06   10.0
7       2023-10-28   10.0
8       2023-07-28    7.0
9       2023-12-31   12.0

## 5.4 Extract Weekday from Transaction Date

In [39]:
transformed_df["Weekday"] = (
    transformed_df["Transaction Date"].dt.day_name()
)

transformed_df[["Transaction Date", "Weekday"]].head(10)

  Transaction Date    Weekday
0       2023-09-08     Friday
1       2023-05-16    Tuesday
2       2023-07-19  Wednesday
3       2023-04-27   Thursday
4       2023-06-11     Sunday
5       2023-03-31     Friday
6       2023-10-06     Friday
7       2023-10-28   Saturday
8       2023-07-28     Friday
9       2023-12-31     Sunday

## 5.5 Extract Year from Transaction Date

In [40]:
transformed_df["Year"] = transformed_df["Transaction Date"].dt.year

transformed_df[["Transaction Date", "Year"]].head(10)

  Transaction Date    Year
0       2023-09-08  2023.0
1       2023-05-16  2023.0
2       2023-07-19  2023.0
3       2023-04-27  2023.0
4       2023-06-11  2023.0
5       2023-03-31  2023.0
6       2023-10-06  2023.0
7       2023-10-28  2023.0
8       2023-07-28  2023.0
9       2023-12-31  2023.0

## 5.6 Create Year-Month Column

In [41]:
transformed_df["Year_Month"] = (
    transformed_df["Transaction Date"].dt.to_period("M").astype("string")
)

transformed_df[["Transaction Date", "Year_Month"]].head(10)

  Transaction Date Year_Month
0       2023-09-08    2023-09
1       2023-05-16    2023-05
2       2023-07-19    2023-07
3       2023-04-27    2023-04
4       2023-06-11    2023-06
5       2023-03-31    2023-03
6       2023-10-06    2023-10
7       2023-10-28    2023-10
8       2023-07-28    2023-07
9       2023-12-31    2023-12

## 5.7 Create Item Category Mapping

In [42]:
category_mapping = {
    "Coffee": "Beverage",
    "Tea": "Beverage",
    "Juice": "Beverage",
    "Smoothie": "Dessert",
    "Salad": "Starter",
    "Cake": "Dessert",
    "Sandwich": "Starter",
    "Cookie": "Dessert",
    "Unknown": "Unknown"
}

transformed_df["Item_Category"] = transformed_df["Item"].map(category_mapping)

transformed_df[["Item", "Item_Category"]].value_counts(dropna=False)

Item      Item_Category
Juice     Beverage         1171
Coffee    Beverage         1165
Salad     Starter          1148
Cake      Dessert          1139
Sandwich  Starter          1131
Smoothie  Dessert          1096
Cookie    Dessert          1092
Tea       Beverage         1089
Unknown   Unknown           969
Name: count, dtype: int64

## 5.8 Validate Transformed Dataset

In [43]:
transformed_df.shape

(10000, 14)

In [44]:
transformed_df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date', 'Revenue', 'Month',
       'Weekday', 'Year', 'Year_Month', 'Item_Category'],
      dtype='str')

In [45]:
# Check unmapped categories

transformed_df.loc[
    transformed_df["Item_Category"].isna(),
    "Item"
].value_counts(dropna=False)

Series([], Name: count, dtype: Int64)

In [46]:
# Convert Month and Year to nullable integers
transformed_df["Month"] = transformed_df["Month"].astype("Int64")
transformed_df["Year"] = transformed_df["Year"].astype("Int64")

# Convert text columns to Pandas string dtype
text_cols = ["Weekday", "Item_Category"]

for col in text_cols:
    transformed_df[col] = transformed_df[col].astype("string")

# Verify the updated data types
transformed_df.dtypes

Transaction ID              string
Item                        string
Quantity                     Int64
Price Per Unit             float64
Total Spent                float64
Payment Method              string
Location                    string
Transaction Date    datetime64[us]
Revenue                    float64
Month                        Int64
Weekday                     string
Year                         Int64
Year_Month                  string
Item_Category               string
dtype: object

## 5.9 Final Transformation Check

In [47]:
transformed_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  string
 1   Item              10000 non-null  string
 2   Quantity          9962 non-null   Int64
 3   Price Per Unit    9962 non-null   float64
 4   Total Spent       9960 non-null   float64
 5   Payment Method    10000 non-null  string
 6   Location          10000 non-null  string
 7   Transaction Date  9540 non-null   datetime64[us]
 8   Revenue           9960 non-null   float64
 9   Month             9540 non-null   Int64
 10  Weekday           9540 non-null   string
 11  Year              9540 non-null   Int64
 12  Year_Month        9540 non-null   string
 13  Item_Category     10000 non-null  string
dtypes: Int64(3), datetime64[us](1), float64(3), string(7)
memory usage: 1.1 MB

In [48]:
transformed_df["Item"].value_counts(dropna = False)

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
Unknown      969
Name: count, dtype: Int64

## 5.10 Final Quality Checks

In [49]:
transformed_df["Transaction ID"].duplicated().sum()

np.int64(0)

In [50]:
transformed_df["Revenue"].equals(transformed_df["Total Spent"])

True

# Milestone 6 - Load into Postgresql

## 6.1 Prepare DataFrame for PostgreSQL

In [51]:
# Create a copy so transformed_df remains unchanged

load_df = transformed_df.copy()

# Rename columns to match the PostgreSQL table
load_df = load_df.rename(
    columns={
    "Transaction ID": "transaction_id",
    "Item": "item",
    "Quantity": "quantity",
    "Price Per Unit": "price_per_unit",
    "Total Spent": "total_spent",
    "Payment Method": "payment_method",
    "Location": "location",
    "Transaction Date": "transaction_date",
    "Revenue": "revenue",
    "Month": "month",
    "Weekday": "weekday",
    "Year": "year",
    "Year_Month": "year_month",
    "Item_Category": "item_category"
})

load_df.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date,revenue,month,weekday,year,year_month,item_category
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,9,Friday,2023,2023-09,Beverage
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,12.0,5,Tuesday,2023,2023-05,Dessert
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,7,Wednesday,2023,2023-07,Dessert
3,TXN_7034554,Salad,2,5.0,10.0,Unknown,Unknown,2023-04-27,10.0,4,Thursday,2023,2023-04,Starter
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,6,Sunday,2023,2023-06,Beverage

In [52]:
load_df.columns.tolist()

['transaction_id',
 'item',
 'quantity',
 'price_per_unit',
 'total_spent',
 'payment_method',
 'location',
 'transaction_date',
 'revenue',
 'month',
 'weekday',
 'year',
 'year_month',
 'item_category']

## 6.2 Validate/Check Dataframe Before Loading

In [53]:
load_df.shape

(10000, 14)

In [54]:
load_df.isna().sum()

transaction_id        0
item                  0
quantity             38
price_per_unit       38
total_spent          40
payment_method        0
location              0
transaction_date    460
revenue              40
month               460
weekday             460
year                460
year_month          460
item_category         0
dtype: int64

In [55]:
load_df

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date,revenue,month,weekday,year,year_month,item_category
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,9,Friday,2023,2023-09,Beverage
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,12.0,5,Tuesday,2023,2023-05,Dessert
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,7,Wednesday,2023,2023-07,Dessert
3,TXN_7034554,Salad,2,5.0,10.0,Unknown,Unknown,2023-04-27,10.0,4,Thursday,2023,2023-04,Starter
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,6,Sunday,2023,2023-06,Beverage
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,Unknown,Unknown,2023-08-30,4.0,8,Wednesday,2023,2023-08,Beverage
9996,TXN_9659401,Unknown,3,1.0,3.0,Digital Wallet,Unknown,2023-06-02,3.0,6,Friday,2023,2023-06,Unknown
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,Unknown,2023-03-02,8.0,3,Thursday,2023,2023-03,Beverage
9998,TXN_7695629,Cookie,3,1.0,3.0,Digital Wallet,Unknown,2023-12-02,3.0,12,Saturday,2023,2023-12,Dessert
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07,12.0,11,Tuesday,2023,2023-11,Starter

## 6.3 Connect Python to PostgreSQL

In [56]:
import os
from dotenv import load_dotenv
from sqlalchemy import create_engine, URL

load_dotenv()

connection_url = URL.create(
    drivername="postgresql+psycopg",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT", "5432")),
    database=os.getenv("DB_NAME")
)

engine = create_engine(connection_url)

In [57]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("SELECT current_database();"))
    print(result.scalar())

sales_etl_db

## 6.4 Load data into PostgreSQL

In [58]:
load_df.to_sql(
    name="cafe_sales",
    con=engine,
    schema="public",
    if_exists="append",
    index=False,
    chunksize=1000
)

-10

## 6.5 Verify the data in PostgreSQL

In [59]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(
        text("SELECT COUNT(*) FROM public.cafe_sales;")
    )
    print("Rows in PostgreSQL:", result.scalar())

Rows in PostgreSQL: 20000

## 6.6 Validate the loaded data

In [60]:
with engine.connect() as connection:
    db_count = connection.execute(
        text("SELECT COUNT(*) FROM public.cafe_sales;")
    ).scalar()

print("Pandas rows:", len(load_df))
print("PostgreSQL rows:", db_count)
print("Row counts match:", len(load_df) == db_count)

Pandas rows: 10000
PostgreSQL rows: 20000
Row counts match: False

In [61]:
null_check_query = text("""
    SELECT
        COUNT(*) FILTER (WHERE quantity IS NULL) AS missing_quantity,
        COUNT(*) FILTER (WHERE price_per_unit IS NULL) AS missing_price,
        COUNT(*) FILTER (WHERE total_spent IS NULL) AS missing_total,
        COUNT(*) FILTER (WHERE transaction_date IS NULL) AS missing_date,
        COUNT(*) FILTER (WHERE revenue IS NULL) AS missing_revenue
    FROM public.cafe_sales;
""")

with engine.connect() as connection:
    result = connection.execute(null_check_query).mappings().one()
    print(dict(result))

{'missing_quantity': 76, 'missing_price': 76, 'missing_total': 80, 'missing_date': 920, 'missing_revenue': 80}

In [62]:
with engine.connect() as connection:
    result = connection.execute(
        text("""
            SELECT *
            FROM public.cafe_sales
            LIMIT 5;
        """)
    )

    for row in result:
        print(row)

('TXN_1961373', 'Coffee', 2, Decimal('2.00'), Decimal('4.00'), 'Credit Card', 'Takeaway', datetime.date(2023, 9, 8), Decimal('4.00'), 9, 'Friday', 2023, '2023-09', 'Beverage')
('TXN_4977031', 'Cake', 4, Decimal('3.00'), Decimal('12.00'), 'Cash', 'In-store', datetime.date(2023, 5, 16), Decimal('12.00'), 5, 'Tuesday', 2023, '2023-05', 'Dessert')
('TXN_4271903', 'Cookie', 4, Decimal('1.00'), Decimal('4.00'), 'Credit Card', 'In-store', datetime.date(2023, 7, 19), Decimal('4.00'), 7, 'Wednesday', 2023, '2023-07', 'Dessert')
('TXN_7034554', 'Salad', 2, Decimal('5.00'), Decimal('10.00'), 'Unknown', 'Unknown', datetime.date(2023, 4, 27), Decimal('10.00'), 4, 'Thursday', 2023, '2023-04', 'Starter')
('TXN_3160411', 'Coffee', 2, Decimal('2.00'), Decimal('4.00'), 'Digital Wallet', 'In-store', datetime.date(2023, 6, 11), Decimal('4.00'), 6, 'Sunday', 2023, '2023-06', 'Beverage')